[package]
name = "nestrs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "*"
statrs = { git = "https://github.com/ColmTalbot/statrs.git", branch = "simpler-sampling" }
logsumexp = "*"
lnexp = "*"
rayon = "*"
rand_chacha = "*"